# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=120, verbose_name='Файл картинки')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Описание')),
                ('alt', models.TextField(verbose_name='Подсказка')),
                ('index', models.IntegerField(verbose_name='Индекс')),
            ],
            options={
                'db_table': 'app_ideator_visuals',
            },
        ),
    ]
