# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-10 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECP_Reestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visual',
            table='wallapers',
        ),
    ]
