# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-12 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECP_Reestr', '0002_auto_20200310_1249'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visual',
            table=None,
        ),
    ]
