# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-12 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECP_Reestr', '0003_auto_20200312_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visual',
        ),
    ]
