# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-10 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access_Request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EP_Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_key', models.BigIntegerField(verbose_name='Номер ключа')),
                ('owner', models.TextField(verbose_name='Владелец ключа')),
                ('date_create', models.DateTimeField(verbose_name='Дата выпуска ЭП')),
                ('date_expired', models.DateTimeField(verbose_name='Дата окончания ЭП')),
                ('for_services', models.TextField(verbose_name='Принадлежность к сервису')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('user_photo', models.FileField(upload_to='', verbose_name='Фото пользователя')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.FileField(default=0, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
