# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access_Request', '0004_auto_20200310_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Введите название сервиса', max_length=200, verbose_name='Наименование сервиса')),
            ],
        ),
        migrations.RemoveField(
            model_name='ep_keys',
            name='for_services',
        ),
        migrations.AddField(
            model_name='ep_keys',
            name='for_services',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='Access_Request.Services', verbose_name='Принадлежность к сервису'),
        ),
    ]
