# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-11 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Access_Request', '0005_auto_20200311_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ep_keys',
            options={'ordering': ['-owner']},
        ),
    ]
