# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-12 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access_Request', '0008_auto_20200312_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Введите название сервиса', max_length=200, verbose_name='Наименование сервиса')),
            ],
        ),
    ]
