# -*- coding: utf-8 -*-
# Generated by Django 3.1.10.17 on 2020-03-12 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Access_Request', '0010_delete_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ep_keys',
            options={'ordering': ['-date_create']},
        ),
    ]
